import { JiraEpicStatusName } from "../jira/issue-epic-status";
import { JiraIssueStatusName } from "../jira/status";

export const jiraIssueEpicStatusByStatus: Record<JiraIssueStatusName, JiraEpicStatusName> = {
  "Awaiting Approval": "To Do",
  Backlog: "To Do",
  Blocked: "To Do",
  "Bug Fixing": "To Do",
  "Build Broken": "To Do",
  Building: "To Do",
  Cancelled: "Done",
  Closed: "Done",
  "Code Review": "In Progress",
  Completed: "Done",
  Delivered: "Done",
  Delivery: "To Do",
  Done: "Done",
  "In Discovery": "In Progress",
  "In Progress": "In Progress",
  "In Review": "In Progress",
  "In Testing": "In Progress",
  "Need Info": "To Do",
  "On Hold": "In Progress",
  Open: "To Do",
  Payed: "To Do",
  "Payment In Progress": "To Do",
  Prepare: "To Do",
  "Ready For Deploy": "In Progress",
  "Ready For Test": "In Progress",
  "Ready For Testing": "In Progress",
  Released: "Done",
  Releasing: "In Progress",
  Reopened: "To Do",
  Resolved: "Done",
  "Selected For Development": "In Progress",
  Snipelt: "To Do",
  Tested: "To Do",
  Testing: "In Progress",
  "Testing On Hold": "In Progress",
  "To Do": "To Do",
  "Waiting For Customer": "To Do",
  "Waiting For Invoice": "To Do",
  "Waiting For Payment": "To Do",
  "Waiting For Release": "To Do",
  "Won't fix": "Done",
  "Готовим К Выдаче": "In Progress",
  "Ожидаем Технику": "In Progress",
};
